name: inspec-openjdk-8-jdk-build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Install InSpec
      run: |
        curl -fsSL https://raw.githubusercontent.com/darkwizard242/devopsubuntu1804/v1.0/packer-build/mods/26-inspec.sh | sudo bash -s -- install
    - name: Install openjdk-8-jdk temporarily
      run: |
        sudo apt-get update
        sudo apt-get install openjdk-8-jdk -y
    - name: Running openjdk8 Inspec Profile
      run: |
        inspec exec . --chef-license accept --no-color
